name: Build and deploy Python app to Azure Web App - stock-backend-clean

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies for Azure App Service
        run: |
          pip install --upgrade pip
          pip install --target="./.python_packages/lib/site-packages" -r requirements.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !.github/
            !antenv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7F76A0C172E84ADFB22A6A44F6A44440 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6720E267C19D46BA8D0F1CA1C9AD515E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3792D9A8422C4279A5F807C202081000 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'stock-backend-clean'
          slot-name: 'Production'
