name: Build and deploy Python app to Azure Web App - stock-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies for Azure App Service
        run: |
          pip install --upgrade pip
          pip install --target="./.python_packages/lib/site-packages" -r requirements.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .python_packages/
            *.py
            requirements.txt
            render.yaml
            style_config.json
            !.github/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D6DF84F5BC514B3783C447A82D566AED }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_87506CD891614877AE8C3400CDBE5058 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_491AAB530FC9489EB1AE01D84462D898 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'stock-backend'
          slot-name: 'Production'
